# Generated by Django 5.2.5 on 2025-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="email подтвержден"),
        ),
    ]
