# Generated by Django 5.2.5 on 2025-09-15 14:40

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="О себе"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[users.validators.birthday_validator],
                verbose_name="День Рождения",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер должен быть формата: '+999999999'",
                        regex="^\\+?1?\\d{8,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=66, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=66, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=66, verbose_name="Фамилия"),
        ),
    ]
