# Generated by Django 5.2.5 on 2025-09-18 14:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[100, 100],
                upload_to="avatars/",
            ),
        ),
    ]
