# Generated by Django 5.2.5 on 2025-09-18 15:38

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.CreateModel(
            name="CustomUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[100, 100],
                        upload_to="avatars/",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер должен быть формата: '+999999999'",
                                regex="^\\+?1?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[users.validators.birthday_validator],
                        verbose_name="День Рождения",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="О себе"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
