# Generated by Django 5.2.5 on 2025-09-18 16:48

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_customuser_avatar_remove_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuserprofile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterField(
            model_name="customuserprofile",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="avatars/default_user.png",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[100, 100],
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="customuserprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
