# Generated by Django 5.2.5 on 2025-09-19 16:03

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.CreateModel(
            name="CourseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_to_complete",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(200),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Часов на выполнение",
                    ),
                ),
                (
                    "number_of_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во учеников"
                    ),
                ),
                (
                    "cover",
                    django_resized.forms.ResizedImageField(
                        crop=["middle", "center"],
                        default="covers/default_cover.png",
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[854, 480],
                        upload_to="covers/",
                        verbose_name="Обложка курса",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_profile",
                        to="main.course",
                        verbose_name="Профиль курса",
                    ),
                ),
            ],
        ),
    ]
