# Generated by Django 5.2.5 on 2025-09-19 17:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_course_updated_at_courseprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["updated_at", "created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="courseprofile",
            options={
                "ordering": ["-number_of_students"],
                "verbose_name": "Профиль курса",
                "verbose_name_plural": "Профили курсов",
            },
        ),
        migrations.AlterField(
            model_name="courseprofile",
            name="cover",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="covers/default_cover.jpeg",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[854, 480],
                upload_to="covers/",
                verbose_name="Обложка курса",
            ),
        ),
    ]
