# Generated by Django 5.2.5 on 2025-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_course_options_alter_courseprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="Описание курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название курса"),
        ),
    ]
