# Generated by Django 5.2.5 on 2025-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_course_options_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, max_length=250, verbose_name="Описание курса"
            ),
        ),
    ]
