# Generated by Django 5.2.5 on 2025-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subblock",
            name="order",
            field=models.PositiveIntegerField(blank=True, verbose_name="Порядок"),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("course", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="subblock",
            unique_together={("block", "order")},
        ),
    ]
