# Generated by Django 5.2.5 on 2025-09-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_subblock_order_alter_block_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={
                "ordering": ["course", "order"],
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
            },
        ),
        migrations.AlterModelOptions(
            name="subblock",
            options={
                "ordering": ["block", "order"],
                "verbose_name": "Подблок",
                "verbose_name_plural": "Подблоки",
            },
        ),
    ]
