#---
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:17-alpine
#        env:
#          POSTGRES_HOST_AUTH_METHOD: trust
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#    steps:
#      - uses: actions/checkout@v3
#      - run: |
#          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
#          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
#          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10.7'
#          cache: pip
#      - run: pip install uv
#      - run: make deps
#      - run: make lint
#      - run: make test
#
#  docker:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: |
#          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> srv/.env
#          echo "DEBUG=${{ secrets.DEBUG }}" >> srv/.env
#          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> srv/.env
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10.7'
#          cache: pip
#      - uses: docker/setup-qemu-action@v3
#      - uses: docker/setup-buildx-action@v3
#      - name: Login to Github Container Registry
#        uses: docker/login-action@v2
#        if: ${{ github.ref == 'refs/heads/master' }}
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build the image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          # push: ${{ github.ref == 'refs/heads/master' }}
#          tags: |
#            ghcr.io/${{ github.repository }}
#            ghcr.io/${{ github.repository }}:${{ github.sha }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
